version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 32771:5432
    environment:
      - POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgrespw
        POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: